routes/web.php
<?php
use App\SentTask;
Route::get('/', function () { 
    return view('auth.login');
});


Route::get('/getDownload/{file_name}','PdfReport@pdf')->name('getDownload');

Route::get("/forgot_password",function(){
	return view('auth.forgot_password');
}); 

Route::post("/forgot_password","UserControoler@forgot_password")->name('forgot_password');
Route::get('task_remiders','ExtraTaskController@task_remiders')->name('task_remiders');
Route::get('/event_user/{id}','EventUserController@show');
//new
Route::get('/statute_report/{id}','StatuteController@show');
Route::post('/matters', 'MatterController@rsave');
Route::post('/matter/time/create','TimesheetController@matterreporters');
Route::post('/matter_time','TimesheetController@store');
Route::post('/matter/time/create','TimesheetController@show');
Route::get('/matter/time/create','TimesheetController@index');
Route::get('/home2', 'HomeController@index2')->name('home2');

//
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('client','ClientController');
	Route::resource('matter','MatterController');
	Route::resource('matter_follow','MatterFollowupController');
	Route::resource('matter_task','TaskController');
	Route::resource('matter_expenses','ExpenseController');
	Route::resource('court_book','CourtBookController');
	Route::resource('opposite_party','OpposingPartyController');
	Route::resource('opposite_advocates','OpposingAdvocatesController');
	Route::resource('court_followup','CourtbookFollowupController');
	Route::resource('billing_type','BillingTypeController');
	Route::resource('practice_area','PracticeAreaController');
	Route::resource('matter_event','MatterEventController');
	Route::resource('party','PartyCOntroller');	
	Route::resource('communication','CommunicationController');
	Route::resource('billing','BillingController');
	Route::resource('matter_witness','MatterWitnessController');
 	Route::get('matter_details/{matter_id}','ExtraTaskController@matter_details');
 	Route::post('change_password','UserControoler@change_password');
 	Route::resource('user','UserControoler');
	Route::resource('alert','AlertController');
	Route::resource('event_user','EventUserController');
	Route::resource('logs','LoggingController');
	Route::resource('matter_authority','MatterAuthorityController');
	Route::resource('parnering_firms','PartneringFirmController');	
	Route::post('change_case_stage','ExtraTaskController@change_case_stage')->name('change_case_stage');
	Route::get('casees_report','ExtraTaskController@casees_report')->name('casees_report');
	Route::post('caseesreport','ExtraTaskController@caseesreport')->name('caseesreport');
	Route::post('matterreport','ExtraTaskController@matterreport')->name('matterreport');
	Route::get('matter_report','ExtraTaskController@matter_report')->name('matter_report');
	Route::post('clientreport','ExtraTaskController@clientreport')->name('clientreport');
	Route::get('client_report','ExtraTaskController@client_report')->name('client_report');
	Route::get('client_list','ExtraTaskController@client_list')->name('client_list');
	Route::post('change_matter_stage','ExtraTaskController@change_matter_stage')->name('change_matter_stage');
	Route::resource('case_types','CaseTypeController');
	Route::resource('company','CompanyController');
});//middleware

app/Matter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Matter extends Model
{
    //
    public function client($value='')
    {
    	# code...
    	return $this->belongsTo('App\Client');
    }

    public function matterfollowup($value='')
    {
    	# code...
    	return $this->hasMany('App\MatterFollowup');
    }

    public function task($value='')
    {
        # code...
        return $this->hasMany('App\Task');
    }

    public function expense($value='')
    {
        # code...
        return $this->hasMany('App\Expense');
    }
   

    public function practicearea($value='')
    {
        # code...
        return $this->belongsToMany('App\PracticeArea','matter_practice_area','matter_id','practiceareas_id');
    }

    public function users($value='')
    {
        # code...
        return $this->belongsToMany('App\User','matter_users');

    }

    public function document($value='')
    {
        # code...ret
        return $this->hasMany('App\Document');

    }

    public function communication($value='')
    {
        return $this->hasMany('App\Communication');
    }

    public function courtbook($value='')
    {
        return $this->hasMany('App\CourtBook');
    }

    public function matterparty()
    {
        return $this->hasMany('App\MatterParty');
    }
    public function opposingadvocates($value='')
    {
        return $this->hasMany('App\OpposingAdvocates','courtbook_id');
    }
    public function timesheet()
    {
        return $this->hasMany(Timesheet::class, 'matternumber');
    }
}

app/Http/Controllers/MatterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\LoggingController;
use Illuminate\Http\Request;
use App\MatterFollowup;
use App\PracticeArea;
use App\Communication;
use App\MatterUser;
use App\Document;
use App\Matter;
use App\Client;

class MatterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $save_log=new LoggingController();
        $save_log->userlog("","MatterUser","Viewing all my matters".$_SERVER['REQUEST_URI']);

        $title="Matters";
        $matters=array();
        // read the matters where I belong
        $checkMatterUser=MatterUser::all()->where('user_id',\Auth::user()->id);
        foreach ($checkMatterUser as $matter_check_value) {
            # code...
            $matters[]=Matter::find($matter_check_value->matter_id);

        }
        // $matters=Matter::all();
        $read_PracticeArea=PracticeArea::all();
        $read_clients=Client::select('id','name','client_number')->where('company_id',\Auth::user()->company_id)->get();
        return view('matter.list')->with(compact('matters','title','read_PracticeArea','read_clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $read_clients=Client::select('id','name','client_number')->where('company_id',\Auth::user()->company_id)->get();
        $read_PracticeArea=PracticeArea::all();
        return view('matter.create')->with(compact('read_clients','read_PracticeArea'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $save_Matter=new Matter();
        $to_date = date_create(str_replace("/", "-", $request->start_date));
        $date_of_registration= date_timestamp_get($to_date);
        $save_Matter->start_date=$date_of_registration;
        $save_Matter->client_id=$request->client_id;
        $save_Matter->name=$request->name;
        $save_Matter->originating_lawyer=$request->originating_lawyer;
        $save_Matter->statutery_limitation=$request->statutery_limitation;
        $save_Matter->description=$request->description;
        $save_Matter->status="Start";      
        $save_Matter->matter_number=$request->matter_number;
        $save_Matter->company_id = \Auth::user()->company_id;
        try {
            $save_Matter->save();

            $save_log=new LoggingController();
            $save_log->userlog($save_Matter->id,"Matter","Creating a matter".$_SERVER['REQUEST_URI']);

            $status="Matter created successfully";

            if (!empty($request->documents)) {
            # save file      
                foreach ($request->documents as $file_value) {
                    $save_Document=new Document();
                    $save_Document->file_title=trim($file_value->getClientOriginalName());
                    // $file_name=trim("themis_file_".time()."_".$file_value->getClientOriginalName());
                    $file_name=trim("themis_file_".time().".".$file_value->getClientOriginalExtension());
                    $save_Document->file_url=$file_name;
                    $save_Document->file_description="None";
                    $save_Document->matter_id= $save_Matter->id;
                    $save_Document->user_id=\Auth::user()->id;                
                    $file_value->move(public_path('documents'),$file_name);
                    $save_Document->save();
                }
            }


            if (!empty($request->practice_area)) {
                foreach ($request->practice_area as $practicearea) {
                    try {
                     \DB::table('matter_practice_area')->insert([['matter_id'=>$save_Matter->id, 'practiceareas_id'=>$practicearea,'created_at'=>date("Y-m-d h:m:s"),'updated_at'=>date("Y-m-d h:m:s")]]);   
                    } catch (\Exception $e) {
                        //echo $e->getMessage();
                         
                    }                              

                }
            }

            if (!empty($request->users)) {                
                foreach ($request->users as $user_value) {
                    $save_MatterUser=new MatterUser();
                    $save_MatterUser->matter_id=$save_Matter->id;
                    $save_MatterUser->user_id=$user_value;
                    if (MatterUser::all()->where('user_id',$user_value)->where('matter_id',$save_Matter->id)->count()==0) {
                        try {
                            $save_MatterUser->save();
                        } catch (\Exception $e) {
                            
                        }

                        try {
                            $send_communication = new Communication();
                            $sms="Dear ".$save_MatterUser->user->name." You have been made an advocate on the matter ".$save_Matter->name.". You should login to view its details.";
                            $send_communication->send_SMS($sms,$save_MatterUser->user->phone_number);
                        
                        } catch (\Exception $e) {}
                    }
                   
                    
                }
            }
        } catch (\Exception $e) {
            //$status=$e->getMessage();
        }


        try {
            $send_communication = new Communication();
            $sms="Dear ".$save_Matter->client->name." Your Matter  ".$save_Matter->name." has been fully registred. Thank you";
            $send_communication->send_Email($save_Matter->client->email,$save_Matter->name,$sms,env("EMAIL_ADDRESS"));
            $send_communication->send_SMS($sms,$save_Matter->client->phone_number); 
            
        } catch (\Exception $e) {}

        return redirect('matter/#profile1')->with(compact('status'));
        //redirect('/posts')->with
    }

// New 
public function rsave(Request $request)
    {
        //
        $save_Matter=new Matter();
        $to_date = date_create(str_replace("/", "-", $request->start_date));
        $date_of_registration= date_timestamp_get($to_date);
        $save_Matter->start_date=$date_of_registration;
        $save_Matter->client_id=$request->client_id;
        $save_Matter->name=$request->name;
        $save_Matter->originating_lawyer=$request->originating_lawyer;
        $save_Matter->statutery_limitation=$request->statutery_limitation;
        $save_Matter->description=$request->description;
        $save_Matter->status="Start";      
        $save_Matter->matter_number=$request->matter_number;
        $save_Matter->company_id = \Auth::user()->company_id;
        try {
            $save_Matter->save();

            $save_log=new LoggingController();
            $save_log->userlog($save_Matter->id,"Matter","Creating a matter".$_SERVER['REQUEST_URI']);

            $status="Matter created successfully, add new Matter";

            if (!empty($request->documents)) {
            # save file      
                foreach ($request->documents as $file_value) {
                    $save_Document=new Document();
                    $save_Document->file_title=trim($file_value->getClientOriginalName());
                    // $file_name=trim("themis_file_".time()."_".$file_value->getClientOriginalName());
                    $file_name=trim("themis_file_".time().".".$file_value->getClientOriginalExtension());
                    $save_Document->file_url=$file_name;
                    $save_Document->file_description="None";
                    $save_Document->matter_id= $save_Matter->id;
                    $save_Document->user_id=\Auth::user()->id;                
                    $file_value->move(public_path('documents'),$file_name);
                    $save_Document->save();
                }
            }


            if (!empty($request->practice_area)) {
                foreach ($request->practice_area as $practicearea) {
                    try {
                     \DB::table('matter_practice_area')->insert([['matter_id'=>$save_Matter->id, 'practiceareas_id'=>$practicearea,'created_at'=>date("Y-m-d h:m:s"),'updated_at'=>date("Y-m-d h:m:s")]]);   
                    } catch (\Exception $e) {
                        //echo $e->getMessage();
                         
                    }                              

                }
            }

            if (!empty($request->users)) {                
                foreach ($request->users as $user_value) {
                    $save_MatterUser=new MatterUser();
                    $save_MatterUser->matter_id=$save_Matter->id;
                    $save_MatterUser->user_id=$user_value;
                    if (MatterUser::all()->where('user_id',$user_value)->where('matter_id',$save_Matter->id)->count()==0) {
                        try {
                            $save_MatterUser->save();
                        } catch (\Exception $e) {
                            
                        }

                        try {
                            $send_communication = new Communication();
                            $sms="Dear ".$save_MatterUser->user->name." You have been made an advocate on the matter ".$save_Matter->name.". You should login to view its details.";
                            $send_communication->send_SMS($sms,$save_MatterUser->user->phone_number);
                        
                        } catch (\Exception $e) {}
                    }
                   
                    
                }
            }
        } catch (\Exception $e) {
            //$status=$e->getMessage();
        }


        try {
            $send_communication = new Communication();

resources/views/matter/edit_matter.blade.php
@extends('layouts.master')

@section('content')
<div class="card-box">
    {{Form::model($read_Matter,['files' => true,'method'=>'PATCH', 'action'=>['MatterController@update',$read_Matter->id]])}}

     <div class="row">
                <div class="col-md-6">
                    @csrf
                    <label>Matter Name</label>
                    <input type="text" name="name" value="{{$read_Matter->name}}" class="form-control">

                    <label>Matter number</label>
                    <input type="text" name="matter_number" value="{{$read_Matter->matter_number}}" class="form-control">

                    <label>Client</label>
                    <select class="form-control select2" name="client_id">
                        <option></option>
                        @foreach($read_clients as $clients)
                          <option value="{{$clients->id}}">{{$clients->name}} {{$clients->client_number}}</option>
                        @endforeach                        
                    </select>

                    <label>Originating Lawyer</label>
                    <select class="form-control select2" name="originating_lawyer">
                        <option></option>
                        @foreach(App\User::all()->where('company_id',Auth::user()->company_id) as $users)
                          <option value="{{$users->id}}">{{$users->name}} ({{$users->phone_number}})</option>
                        @endforeach                        
                    </select>
                 
                    <label>Start date</label>
                    <input type="date" name="start_date" value="{{$read_Matter->start_date}}" class="form-control">

                    <label>Statutory limitation</label>
                    <input type="date" name="statutery_limitation" value="{{$read_Matter->statutery_limitation}}" class="form-control">

                    <label>Description</label>
                    <input type="text" name="description" value="{{$read_Matter->description}}" class="form-control">

                    <label>Parties</label>
                    <input type="text" name="parties" value="{{$read_Matter->parties}}" class="form-control">


                    <br>
                    <button class="btn btn-primary" type="submit">Save</button>

                </div>

            <div class="col-md-6">              
                <label>Practice area</label>
                <select class="form-control" name="practice_area[]" multiple="multiple" id="fsg_service_id_community">
                    <option></option>
                    @foreach($read_PracticeArea as $practicearea)
                      <option value="{{$practicearea->id}}">{{$practicearea->name}}</option>
                    @endforeach
                </select>
<br>

                <br>

                <select class="form-control" name="users[]" multiple="multiple" id="my_multi_select3">
                    <option></option>
                    @foreach(App\User::all()->where('company_id',Auth::user()->company_id) as $users)
                      <option value="{{$users->id}}">{{$users->name}}</option>
                    @endforeach
                </select>

                <label>Any files</label><br>
                <input type="file" name="documents[]" multiple="multiple">
                
            </div>
        </div>
        {{Form::close()}}
    </div>
@endsection

resources/views/matter/list.blade.php
@extends('layouts.master')

@section('content')
 <div class="card-box">

    <ul class="nav nav-tabs m-b-10" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#home1" role="tab" aria-controls="profile">Add new matter</a>
        </li>  

        <li class="nav-item">
            <a class="nav-link" id="home-tab" data-toggle="tab" href="#profile1" role="tab" aria-controls="home" aria-expanded="true">Matters</a>
        </li> 
        
        <!-- N.E <li class="nav-item">
          <a class="nav-link" id="home-tab2" data-toggle="tab" href="#profile2" role="tab" aria-controls="home" aria-expanded="true">Add Time Spent</a>
      </li> -->                  
    </ul>
 

     <div class="tab-content">
        <div class="tab-pane active" id="home1">

            <form method="POST" action="{{route('matter.store')}}" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-6">
                        @csrf
                        <label>Matter Name</label>
                        <input type="text" name="name" class="form-control">

                        <label>Matter number</label>
                        <input type="text" name="matter_number" class="form-control">

                        <label>Client</label>
                        <select class="form-control select2" name="client_id">
                            <option></option>
                            @foreach($read_clients as $clients)
                              <option value="{{$clients->id}}">{{$clients->name}} {{$clients->client_number}}</option>
                            @endforeach                        
                        </select>

                        <label>Originating Lawyer</label>
                        <select class="form-control select2" name="originating_lawyer">
                            <option></option>
                            @foreach(App\User::all()->where('company_id',Auth::user()->company_id) as $users)
                              <option value="{{$users->id}}">{{$users->name}} ({{$users->phone_number}})</option>
                            @endforeach                        
                        </select>
                        

                        <label>Start date</label>
                        <input type="date" name="start_date" class="form-control">

                        <label>Statutory limitation</label>
                        <input type="date" name="statutery_limitation" class="form-control">
                        <br>
                        <label>Description</label>
                        <textarea name="description" class="form-control"></textarea><br>
                        <button class="btn btn-primary" type="submit">Save</button>
                  <!--new-->
                    <form action="/matters" method="POST">
                      @csrf
                  <button class="btn btn-success" type="submit"> Save and Add New</strong></button>
                  
                  </form>
              
                  <!--endNew-->
                </div>

                <div class="col-md-6">
                    <label>Practice area</label>
                    <select class="multi-select" name="practice_area[]" multiple="multiple" id="fsg_service_id_community">
                        <option></option>
                        @foreach($read_PracticeArea as $practicearea)
                          <option value="{{$practicearea->id}}">{{$practicearea->name}}</option>
                          <?php
                            
                          ?>
                        @endforeach
                    </select>

                    <br>
                   
                    <select name="practice_area[]" id="fsg_service_id_community">
                        @foreach ($read_PracticeArea as $practicearea)
                        <option value="{{$practicearea->id}}">{{$practicearea->name}}</option>
                        @endforeach
                    
                    </select> 
                    <br>

                    <label>Advocates Involved</label>
                    <select class="multi-select" name="users[]" multiple="multiple" id="my_multi_select3">
                        <option></option>
                        @foreach(App\User::all()->where('company_id',Auth::user()->company_id) as $users)
                          <option value="{{$users->id}}">{{$users->name}}</option>
                        @endforeach
                    </select>

                    <label>Any files?</label><br>
                    <input type="file" name="documents[]" multiple="multiple">
                    
                </div>
            </div>
           </form>

        </div>

         <div class="tab-pane" id="profile1">

            <form method="POST" action="{{url('change_matter_stage')}}">
                @csrf

             <table class="table" id="matters">
                <thead>
                  <th>Date</th>  <th>Client Name</th> <th>Matter</th> <th>Number</th> <th>Start date</th> <th>Matter Stage</th>
                 <th></th><th>Change stage</th>
                </thead>

                <tbody>
                    @foreach($matters as $matter)
                      <tr>
                        <td>{{$matter->created_at}}</td>
                        <td><a href="{{route('client.show',$matter->client->id)}}">{{$matter->client->name}}</a></td>
                        <td><a href="/matter_details/{{$matter->id}}">{{$matter->name}}</a></td>
                        <td><a href="/matter_details/{{$matter->id}}">{{$matter->matter_number}}</a></td>
                        <td>{{date('d-m-Y',$matter->start_date)}}</td>
                        <td>
                            @if($matter->status=="Start")
                              <span class="btn btn-danger">{{$matter->status}}</span>

                              @elseif($matter->status=="process")

                              <span class="btn btn-warning">{{$matter->status}}</span>

                               @elseif($matter->status=="done")

                              <span class="btn btn-success">{{$matter->status}}</span>


                            @endif

                        </td>
                        <td>
                            @if($matter->status=="done")

                               @else
                                <a href="{{route('matter.edit',$matter->id)}}" class="btn btn-primary">Edit</a>
                            @endif 
                        </td>
                        <td>
                            <input type="checkbox" name="matter[]" value="{{$matter->id}}">
                        </td>
                      </tr>
                    @endforeach
                </tbody>
              </table>
              <br>
            <label>Stage</label>
            <select class="form-control" name="stage">
                <option></option>
                <option value="Start">Start</option>
                <option value="process">Under process</option>
                <option value="done">Done</option>
            </select>
            <br>
            <button type="submit" class="btn btn-primary">Change Matter stage</button>
          </form>

        </div>
        <div class="tab-pane" id="profile2">
          <form action="/matter_time" method="POST">
            {{ csrf_field() }}
                 <div class="row">
                            <div class="col-md-6">
                                
                                <label>Matter Name</label>
                                
                                <select class="form-control inputstl" name="mattername">
                                      @foreach($matters as $matter)
                                  <option value="{{$matter->name}}">{{$matter->name}}</option>
                                    @endforeach
                                </select>
                                <br>
                                
                            <!--<input type="text" name="mattername" class="form-control">
                            --> <label>Date </label>
                                <input type="date" name="date" placeholder="YYYY-MM-DD" class="form-control">
                                <label>Time in hours</label>
                                <input class="form-control inputstl" type="number" name="timeinhours" placeholder="Time in hours">
            
                                <br>
                                <form method="POST" action="/matter_time">
                                  @csrf
                                <input class="btn btn-success" name="submit" type="submit" value="Save"/>
                                </form>
                              </div>
                 </div>
            </form>

      </div>
    </div>
</div>
   
@endsection

resources/views/matter/recorded_details.blade.php
@extends('layouts.master')

@section('content')

	<div class="card-box">
		<h3>{{$read_MatterFollowup->title}}</h3>
		<span>Date: {{date('d-m-Y',$read_MatterFollowup->date_created)}}</span>
		<br><br>
		<span>
			{{$read_MatterFollowup->description}}
		</span>
		<br>

	  	@foreach($read_MatterFollowup->document as $files)
	  	    <a href="/getDownload/{{$files->file_url}}">Here</a>
      		<a href="{{asset('documents')}}/{{$files->file_url}}">{{$files->file_title}}</a><br>
    	@endforeach 
    	<br>
    	<span>Recorded by {{$read_MatterFollowup->user->name}}</span>
	 
	</div>   
@endsection

resources/views/matter/witness.blade.php
@extends('layouts.master')
@section('content')
<div class="card-box">
    <!-- <form method="POST" action="{{route('matter_witness.store')}}"> -->
        <div class="row">
            <div class="col-md-6">
                @csrf
                <label>Name</label>
                <input type="text" id="name" class="form-control">

                <input type="hidden" id="matter_id" value="{{$read_Matter->id}}">

                <label>Phone Number</label>
                <input type="text" id="phone_number" class="form-control">

                <label>Address</label>
                <input type="text" id="address" class="form-control">              

                <br>
                <button class="btn btn-primary" id="newpar" type="submit">Save</button>
            </div>
        </div>
   <!-- </form>   -->
</div>  
@endsection


@push('scripts')
  <script type="text/javascript">
    $("#newpar").click(function() {
        $.ajax({
                type: "POST",
                url: "{{ route('matter_witness.store') }}",
            data: {
                name: $("#name").val(),
                address: $("#address").val(),
                phone_number: $("#phone_number").val(),
                matter_id:$("#matter_id").val(),              
                _token: "{{Session::token()}}"
            },
                success: function(result){
                    alert(result);
                    $("#name").val(" ");
                    $("#address").val(" ");
                    $("#phone_number").val(" ") ;                   
                }
        })
    });
  </script>
@endpush