routes/web.php
<?php
use App\SentTask;
Route::get('/', function () { 
    return view('auth.login');
});


Route::get('/getDownload/{file_name}','PdfReport@pdf')->name('getDownload');

Route::get("/forgot_password",function(){
	return view('auth.forgot_password');
}); 

Route::post("/forgot_password","UserControoler@forgot_password")->name('forgot_password');
Route::get('task_remiders','ExtraTaskController@task_remiders')->name('task_remiders');
Route::get('/event_user/{id}','EventUserController@show');
//new
Route::get('/statute_report/{id}','StatuteController@show');
Route::post('/matters', 'MatterController@rsave');
Route::post('/matter/time/create','TimesheetController@matterreporters');
Route::post('/matter_time','TimesheetController@store');
Route::post('/matter/time/create','TimesheetController@show');
Route::get('/matter/time/create','TimesheetController@index');
Route::get('/home2', 'HomeController@index2')->name('home2');

//
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('client','ClientController');
	Route::resource('matter','MatterController');
	Route::resource('matter_follow','MatterFollowupController');
	Route::resource('matter_task','TaskController');
	Route::resource('matter_expenses','ExpenseController');
	Route::resource('court_book','CourtBookController');
	Route::resource('opposite_party','OpposingPartyController');
	Route::resource('opposite_advocates','OpposingAdvocatesController');
	Route::resource('court_followup','CourtbookFollowupController');
	Route::resource('billing_type','BillingTypeController');
	Route::resource('practice_area','PracticeAreaController');
	Route::resource('matter_event','MatterEventController');
	Route::resource('party','PartyCOntroller');	
	Route::resource('communication','CommunicationController');
	Route::resource('billing','BillingController');
	Route::resource('matter_witness','MatterWitnessController');
 	Route::get('matter_details/{matter_id}','ExtraTaskController@matter_details');
 	Route::post('change_password','UserControoler@change_password');
 	Route::resource('user','UserControoler');
	Route::resource('alert','AlertController');
	Route::resource('event_user','EventUserController');
	Route::resource('logs','LoggingController');
	Route::resource('matter_authority','MatterAuthorityController');
	Route::resource('parnering_firms','PartneringFirmController');	
	Route::post('change_case_stage','ExtraTaskController@change_case_stage')->name('change_case_stage');
	Route::get('casees_report','ExtraTaskController@casees_report')->name('casees_report');
	Route::post('caseesreport','ExtraTaskController@caseesreport')->name('caseesreport');
	Route::post('matterreport','ExtraTaskController@matterreport')->name('matterreport');
	Route::get('matter_report','ExtraTaskController@matter_report')->name('matter_report');
	Route::post('clientreport','ExtraTaskController@clientreport')->name('clientreport');
	Route::get('client_report','ExtraTaskController@client_report')->name('client_report');
	Route::get('client_list','ExtraTaskController@client_list')->name('client_list');
	Route::post('change_matter_stage','ExtraTaskController@change_matter_stage')->name('change_matter_stage');
	Route::resource('case_types','CaseTypeController');
	Route::resource('company','CompanyController');
});//middleware

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    //
    public function matter($value='')
    {
    	# code...
    	return $this->hasMany('App\Matter');
    }

    public function user($value='')
    {
    	return $this->belongsTo('App\User');
    }
    public function statute($value='')
    {
    	return $this->hasOne('App\Statute');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\LoggingController;
use App\BillingType;
use App\Communication;
use App\Client;
use App\MatterEvent;
use App\User;
// use Auth;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $read_clients=Client::all()->where('company_id',\Auth::user()->company_id);
        return view('client.list')->with(compact('read_clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $read_BillingType=BillingType::all();
        $read_clients=Client::all()->where('company_id',\Auth::user()->company_id);
        $title="Client";
        return view('client.create')->with(compact('read_BillingType','title','read_clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        //
        $ids = Client::pluck('client_number')->toArray();    
        do {
                $id = date("y-").rand(001, 999);
        } while (in_array($id, $ids));
                
        //echo $id;
        //
         $this->validate($request,["name"=>"required","client_type"=>"required","address"=>"required","phone_number"=>"required","date_registered"=>"required"]);
        $save_Client=new Client();
        $save_Client->name=$request->name;
        $save_Client->client_type=$request->client_type;
        $save_Client->address=$request->address;
        $save_Client->phone_number=$request->phone_number;
        $save_Client->phone_number_2=$request->phone_number_2;
        $save_Client->contact_person=$request->contact_person;
        $save_Client->email=$request->email;
        $save_Client->client_number=$id;
        $save_Client->tin_number=$request->tin_number;
        $save_Client->reffered_by=$request->reffered_by;
        $save_Client->referred_by_phone=$request->referred_by_phone;
        $save_Client->referred_by_name=$request->referred_by_name;
        $save_Client->company_id = \Auth::user()->company_id;
        
        
        //$save_Client->client_no = str_pad(1, 6, "18-", STR_PAD_LEFT);
        //str_pad($ids[0]->Auto_increment, 5, '0', STR_PAD_LEFT);
        //$generateOrder_nr = '#' . str_pad(1, 8, "0", STR_PAD_LEFT);
        
        $to_date = date_create(str_replace("/", "-", $request->date_registered));
        $date_of_registration= date_timestamp_get($to_date);

        $save_Client->date_registered=$date_of_registration;
        // $save_Client->billingtype_id=$request->billingtype_id;
        $save_Client->user_id=\Auth::user()->id;
        try {
            $save_Client->save();
            $status="Client created successfully.";
            
            $save_log=new LoggingController();
            $save_log->userlog($save_Client->id,"Client","Creating a client ".$_SERVER['REQUEST_URI']);
            
        } catch (\Exception $e) {
            //$status=$e->getMessage();
        }

        try {
            $send_communication = new Communication();

            $sms="Dear ".$save_Client->name." your Matter is being initiated.";
 
            $send_communication->send_SMS($sms,$save_Client->phone_number); 
            
        } catch (\Exception $e) {}
       
        return redirect()->route('matter.index')->with(compact('status'));
        //return redirect()->route('client.create')->with(compact('status'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $read_Client=Client::find($id);
        $title="Details for ".$read_Client->name;
         return view('client.single_user')->with(compact('read_Client','title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $read_Client=Client::find($id);
        $read_BillingType=BillingType::all();
        $title="Edit data for ".$read_Client->name;
        return view('client.update')->with(compact('read_Client','read_BillingType','title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $read_Client=Client::find($id);

        if (!empty($request->name)) {
            # code...
            $read_Client->name=$request->name;
        }
        
        if (!empty($request->client_type)) {
            # code...
            $read_Client->client_type=$request->client_type;
        }

        if (!empty($request->address)) {
            # code...
            $read_Client->address=$request->address;
        }

        if (!empty($request->phone_number)) {
            # code...
             $read_Client->phone_number=$request->phone_number;
        }
        if (!empty($request->phone_number_2)) {
            # code...
             $read_Client->phone_number_2=$request->phone_number_2;
        }

        if (!empty($request->$request->reffered_by)) {
            # code...
            $read_Client->reffered_by=$request->reffered_by;
        } 

        if (!empty($request->contact_person)) {
                $read_Client->contact_person=$request->contact_person;
            }

        if (!empty($request->referred_by_phone)) {
          $read_Client->referred_by_phone=$request->referred_by_phone;
         } 

         if (!empty($request->referred_by_name)) {
             $read_Client->referred_by_name=$request->referred_by_name;
         }
        
        if (!empty($request->email)) {
             $read_Client->email=$request->email;
           }
        if (!empty($request->client_number)) {
            $read_Client->client_number=$request->client_number;
           }   
        
        if (!empty($request->date_registered)) {
            # code...
            $to_date = date_create(str_replace("/", "-", $request->date_registered));
            $date_of_registration= date_timestamp_get($to_date);
            $read_Client->date_registered=$date_of_registration;
        }
        
        if (!empty($request->billingtype_id)) {
            $read_Client->billingtype_id=$request->billingtype_id;
        }
        
        $read_Client->user_id=\Auth::user()->id;
        try {
            $read_Client->save();
            $status="Client Updated successfully.";

            $save_log=new LoggingController();
            $save_log->userlog($read_Client->id,"Client","Updating a client ".$_SERVER['REQUEST_URI']);

        } catch (\Exception $e) {
            //$status=$e->getMessage();
        }

        return redirect()->route('client.create')->with(compact('status'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {          
            Client::destroy($id);
            $save_log=new LoggingController();
            $save_log->userlog($id,"Client","Deleting a client");
        } catch (\Exception $e) {
           return redirect()->route('client.index')->with(compact('status')); 
        }
    }
}

resources/views/client/create.blade.php
@extends('layouts.master')

@section('content')
        <div class="card-box">
            <ul class="nav nav-tabs m-b-10" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" id="home-tab" data-toggle="tab" href="#home1" role="tab" aria-controls="home" aria-expanded="true">Add new client</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile1" role="tab" aria-controls="profile">View Clients</a>
                </li>              
            </ul>
       
 
            <div class="tab-content">
                <div class="tab-pane" id="home1">
                    <form method="POST" action="{{route('client.store')}}">
                        <div class="row">
                            <div class="col-md-6">
                                @csrf
                                <label>Client Name</label>
                                <input type="text" name="name" value="{{old('name')}}" class="form-control">

                                <!--<label>Client number</label>
                                <input type="text" name="client_number" class="form-control">

                                <br>
                                -->
                                <label>TIN Number</label>
                                <input type="text" name="tin_number" class="form-control">

                                <br>

                                <label>Client type</label>
                                <select class="form-control" id="client_type" name="client_type">
                                    <option></option>
                                    <option value="individual">Individual</option>
                                    <option value="company">Company</option>
                                </select>
                                &nbsp;
                                <br>

                                <label>Address</label>
                                <input type="text" name="address" class="form-control">

                                <label>Phone Number</label>
                                <input type="text" name="phone_number" class="form-control">
            
                                <br>
                                <label>Secondary Phone Number</label>
                                <input type="text" name="phone_number_2" class="form-control">

                                <br>
                                <button type="submit" class="btn btn-primary waves-effect w-md waves-light m-b-5">Save</button>
                            </div>

                            <div class="col-md-6">
                                <span class="contral_section">                            
                                    <label>Contact Person</label>
                                    <input type="text" name="contact_person" class="form-control">
                                </span>

                                <label>Email Address</label>
                                <input type="email" name="email" class="form-control">

                                <label>Referred by</label>
                                <select class="form-control" id="reffered_by" name="reffered_by">
                                    <option></option>
                                    <option value="institution">Institution</option>
                                    <option value="individual">Individual</option>
                                    <option value="Self">Self referred</option>
                                </select>

                            <span class="refree_section">

                                <label>Name of referee</label>
                                <input type="text" name="referred_by_name" class="form-control">

                                <label>Phone Number of referee</label>
                                <input type="text" name="referred_by_phone" class="form-control">
                              </span>

                                <label>Date registered</label>
                                <input type="date" name="date_registered" class="form-control"> 
                          
                                <br>                            
                                
                            </div>
                        </div>
                    </form>
                   
                </div>


                <div class="tab-pane active" id="profile1">

                    <table class="table table-hover table-striped" id="clients">
                        <thead>
                           <th>#</th> <th>Date registered</th> <th>Name</th>  <th>Phone Number</th> <th>Secondary Phone Number</th> <th>Client Number</th> <th>Client Type</th> <th>By</th> <th></th>
                        </thead>

                        <tbody>
                            @foreach($read_clients as $clients)
                              <tr>
                                  <td>{{$clients->id}}</td>
                                  <td>{{date('d-m-Y',$clients->date_registered)}}</td>
                                  <td><a href="{{route('client.show',$clients->id)}}">{{$clients->name}}</a></td>
                                
                                  <td>{{$clients->phone_number}}</td>
                                  <td>{{$clients->phone_number_2}}</td>
                                   <td>{{$clients->client_number}}</td>
        
                                   <td>{{$clients->client_type}}</td>
                                   <td>{{$clients->user->name}}</td>
                                   <td>
                                    <a class="btn btn-primary" href="{{route('client.edit',$clients->id)}}">Edit</a>
                                    <!-- <a href="{{route('event_user.show',$clients->id)}}" class="btn btn-success">Report</a> -->
                                   </td>
                              </tr>
                            @endforeach
                        </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    @endsection

    @push('scripts')
       <script type="text/javascript">
            $(document).ready(function() {
                $('#client_type').on('change',function(e){
                    if ($("#client_type").val() == "individual") {
                        $(".contral_section").hide();
                    }
                    else{
                        $(".contral_section").show();
                    }
               
                }) 
            })
       </script>

        <script type="text/javascript">
            $(document).ready(function() {
                $('#reffered_by').on('change',function(e){
                    if ($("#reffered_by").val() == "Self") {
                        $(".refree_section").hide();
                    }
                    else{
                        $(".refree_section").show();
                    }
               
                }) 
            })
       </script>
    @endpush

resources/views/client/single_user.blade.php
@extends('layouts.master')
@section('content')

<div class="card-box">
	<div class="row">
		<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
			<table class="table table-hover table-striped" id="clients">
				<tr>
					<td>Client number </td><td><b>{{$read_Client->client_number}}</b></td>
				</tr>

				<tr>
					<td>Client Type: </td><td><b>{{$read_Client->client_type}}</b></td>
				</tr>

				<tr>
					<td>Address: </td><td><b>{{$read_Client->address}}</b></td>
				</tr>

				<tr>
					<td>Phone Number: </td><td><b>{{$read_Client->phone_number}}</b></td>
				</tr>
				<tr>
					<td>Secondary Phone Number: </td><td><b>{{$read_Client->phone_number_2}}</b></td>
				</tr>
				<tr>
					<td>Contact person: </td><td><b>@if($read_Client->client_type == "individual" ) Self @else {{$read_Client->contact_person}} @endif</b></td>
				</tr>

				<tr>
					<td>Email: </td><td><b>{{$read_Client->email}}</b></td>
				</tr>

				<tr>
					<td>Reffered by: </td><td><b>{{$read_Client->reffered_by}} ( {{$read_Client->referred_by_name}} {{$read_Client->referred_by_phone}})</b></td>
				</tr>

				<tr>
					<td>Date registered: </td><td><b>{{date('d-m-Y',$read_Client->date_registered)}}</b></td>
				</tr>

				<tr>
					<td>Created By: </td><td><b>{{$read_Client->user->name}}</b></td>
				</tr>
			</table>
		</div>
	</div>
</div>

<div class="card-box">
		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
				<table class="table table-hover table-striped" id="clients">
				<tr>
				<th>Matters</th><th>Start Date of Matters</th>
			</tr>
			<tr>
				<td>
						
						@foreach($read_Client->matter as $matter)
                            <tr>
								<td>{{$matter->name}}</td><td>{{date('d-m-Y',$matter->start_date)}}
							</tr>
                        @endforeach
				</td>
			</tr>
			</table>
			</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/client/update.blade.php
@extends('layouts.master')

@section('content')
<div class="card-box">
    {{Form::model($read_Client,['method'=>'PATCH', 'action'=>['ClientController@update',$read_Client->id]])}}
        <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">

                <label>Client Name</label>
                <input type="text" name="name" value="{{$read_Client->name}}" class="form-control">

                <!--<label>Client number</label>
                <input type="text" name="client_number" value="{{$read_Client->client_number}}" class="form-control">
                -->
                <label>Tin Number</label>
                <input type="text" name="tin_number" value="{{$read_Client->tin_number}}" class="form-control">

                <label>Client type</label>
                <select class="form-control" name="client_type" id="client_type">
                    <option></option>
                    <option value="individual">Individual</option>
                    <option value="company">Company</option>
                </select>

                <label>Address</label>
                <input type="text" name="address" value="{{$read_Client->address}}" class="form-control">

                <label>Phone Number</label>
                <input type="text" name="phone_number" value="{{$read_Client->phone_number}}" class="form-control">
                <br>
                <label>Secondary Phone Number</label>
                <input type="text" name="phone_number" value="{{$read_Client->phone_number_2}}" class="form-control">
                <br>
                <button class="btn btn-primary" type="submit">Save</button>                
            </div>

             <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
               <span class="contral_section">
                    <label>Contact Person</label>
                    <input type="text" name="contact_person" value="{{$read_Client->contact_person}}" class="form-control">
                </span>

                <label>Email Address</label>
                <input type="email" name="email" value="{{$read_Client->email}}" class="form-control">

                <label>Referred by</label>
                <select class="form-control select2" id="reffered_by" name="reffered_by">
                    <option></option>
                    <option value="institution">Institution</option>
                    <option value="individual">Individual</option>
                    <option value="Self">Self referred</option>
                </select>

                <span class="refree_section">

                    <label>Name of referee</label>
                    <input type="text" name="referred_by_name" value="{{$read_Client->referred_by_name}}" class="form-control">

                    <label>Phone Number of referee</label>
                    <input type="text" name="referred_by_phone" value="{{$read_Client->referred_by_phone}}" class="form-control">
                </span>

                <label>Date registered</label>
                <input type="date" name="date_registered" value="{{$read_Client->date_registered}}" class="form-control">             
        
            </div>
        </div>
    </div>
    {{Form::close()}}
@endsection
@push('scripts')
   <script type="text/javascript">
        $(document).ready(function() {
            $('#client_type').on('change',function(e){
                if ($("#client_type").val() == "individual") {
                    $(".contral_section").hide();
                }
                else{
                    $(".contral_section").show();
                }
           
            }) 
        })
   </script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#reffered_by').on('change',function(e){
                if ($("#reffered_by").val() == "Self") {
                    $(".refree_section").hide();
                }
                else{
                    $(".refree_section").show();
                }           
            }) 
        })
   </script>
@endpush