routes/web.php
<?php
use App\SentTask;
Route::get('/', function () { 
    return view('auth.login');
});


Route::get('/getDownload/{file_name}','PdfReport@pdf')->name('getDownload');

Route::get("/forgot_password",function(){
	return view('auth.forgot_password');
}); 

Route::post("/forgot_password","UserControoler@forgot_password")->name('forgot_password');
Route::get('task_remiders','ExtraTaskController@task_remiders')->name('task_remiders');
Route::get('/event_user/{id}','EventUserController@show');
//new
Route::get('/statute_report/{id}','StatuteController@show');
Route::post('/matters', 'MatterController@rsave');
Route::post('/matter/time/create','TimesheetController@matterreporters');
Route::post('/matter_time','TimesheetController@store');
Route::post('/matter/time/create','TimesheetController@show');
Route::get('/matter/time/create','TimesheetController@index');
Route::get('/home2', 'HomeController@index2')->name('home2');

//
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('client','ClientController');
	Route::resource('matter','MatterController');
	Route::resource('matter_follow','MatterFollowupController');
	Route::resource('matter_task','TaskController');
	Route::resource('matter_expenses','ExpenseController');
	Route::resource('court_book','CourtBookController');
	Route::resource('opposite_party','OpposingPartyController');
	Route::resource('opposite_advocates','OpposingAdvocatesController');
	Route::resource('court_followup','CourtbookFollowupController');
	Route::resource('billing_type','BillingTypeController');
	Route::resource('practice_area','PracticeAreaController');
	Route::resource('matter_event','MatterEventController');
	Route::resource('party','PartyCOntroller');	
	Route::resource('communication','CommunicationController');
	Route::resource('billing','BillingController');
	Route::resource('matter_witness','MatterWitnessController');
 	Route::get('matter_details/{matter_id}','ExtraTaskController@matter_details');
 	Route::post('change_password','UserControoler@change_password');
 	Route::resource('user','UserControoler');
	Route::resource('alert','AlertController');
	Route::resource('event_user','EventUserController');
	Route::resource('logs','LoggingController');
	Route::resource('matter_authority','MatterAuthorityController');
	Route::resource('parnering_firms','PartneringFirmController');	
	Route::post('change_case_stage','ExtraTaskController@change_case_stage')->name('change_case_stage');
	Route::get('casees_report','ExtraTaskController@casees_report')->name('casees_report');
	Route::post('caseesreport','ExtraTaskController@caseesreport')->name('caseesreport');
	Route::post('matterreport','ExtraTaskController@matterreport')->name('matterreport');
	Route::get('matter_report','ExtraTaskController@matter_report')->name('matter_report');
	Route::post('clientreport','ExtraTaskController@clientreport')->name('clientreport');
	Route::get('client_report','ExtraTaskController@client_report')->name('client_report');
	Route::get('client_list','ExtraTaskController@client_list')->name('client_list');
	Route::post('change_matter_stage','ExtraTaskController@change_matter_stage')->name('change_matter_stage');
	Route::resource('case_types','CaseTypeController');
	Route::resource('company','CompanyController');
});//middleware

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="icon" type="icon" href="{{asset('documents/logo.png')}}">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                 <!--    <ul class="navbar-nav mr-auto">
                        <li><a href="{{route('client.index')}}">Clients</a></li>    |                        
                        <li><a href="{{route('matter.index')}}">Matters</a></li>    |   
                        <li><a href="{{route('matter_task.index')}}">My Tasks</a></li>  |
                        <li><a href="{{route('matter_expenses.index')}}">My Expenses</a></li> | 
                        <li><a href="{{route('court_book.index')}}">Court book</a></li> 
                    </ul> -->

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/login_master.blade.php
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured system for Law firms.">
        <meta name="author" content="Thembo Charles Lwanga (Veritas Interactive ltd - Hive Colab)">

        <!-- App Favicon -->
          <link rel="icon" href="{{asset('documents/favicon.PNG')}}">

        <!-- App title -->
         <title>{{ config('app.name', '') }}</title>

        <!-- App CSS -->
        <link href="{{asset('back_end/assets/css/style.css')}}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <script src="{{asset('back_end/assets/js/modernizr.min.js')}}"></script>
    </head>


    <body>

        <div class="account-pages"></div>
        <div class="clearfix"></div>
        <div class="wrapper-page">

               <!-- ============================================================== -->
               <!--  Blade template -->
                <!-- ============================================================== -->
                        @yield('content')
                <!-- ============================================================== -->
                <!-- End Blade template -->
                <!-- ============================================================== -->          

        </div>
        <!-- end wrapper page -->


        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <!-- jQuery  -->
        <script src="{{asset('back_end/assets/js/jquery.min.js')}}"></script>
        <script src="{{asset('back_end/assets/js/tether.min.js')}}"></script><!-- Tether for Bootstrap -->
        <script src="{{asset('back_end/assets/js/bootstrap.min.js')}}"></script>
        <script src="{{asset('back_end/assets/js/waves.js')}}"></script>
        <script src="{{asset('back_end/assets/js/jquery.nicescroll.js')}}"></script>
        <script src="{{asset('back_end/assets/plugins/switchery/switchery.min.js')}}"></script>

        <!-- App js -->
        <script src="{{asset('back_end/assets/js/jquery.core.js')}}"></script>
        <script src="{{asset('back_end/assets/js/jquery.app.js')}}"></script>

        <script type="text/javascript">
            $(document).ready(function() {
            setInterval(function() {
                verify_response()
            }, 10000);
            });

            function verify_response() {
            $.ajax({
                    type: "GET",
                    url: "/task_remiders",
                    data: {                
                        _token: "{{Session::token()}}" },
                    success: function(result){
                    console.log(result);
                    }
                })
            }
        </script>

    </body>
</html>