routes/web.php
<?php
use App\SentTask;
Route::get('/', function () { 
    return view('auth.login');
});


Route::get('/getDownload/{file_name}','PdfReport@pdf')->name('getDownload');

Route::get("/forgot_password",function(){
	return view('auth.forgot_password');
}); 

Route::post("/forgot_password","UserControoler@forgot_password")->name('forgot_password');
Route::get('task_remiders','ExtraTaskController@task_remiders')->name('task_remiders');
Route::get('/event_user/{id}','EventUserController@show');
//new
Route::get('/statute_report/{id}','StatuteController@show');
Route::post('/matters', 'MatterController@rsave');
Route::post('/matter/time/create','TimesheetController@matterreporters');
Route::post('/matter_time','TimesheetController@store');
Route::post('/matter/time/create','TimesheetController@show');
Route::get('/matter/time/create','TimesheetController@index');
Route::get('/home2', 'HomeController@index2')->name('home2');

//
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('client','ClientController');
	Route::resource('matter','MatterController');
	Route::resource('matter_follow','MatterFollowupController');
	Route::resource('matter_task','TaskController');
	Route::resource('matter_expenses','ExpenseController');
	Route::resource('court_book','CourtBookController');
	Route::resource('opposite_party','OpposingPartyController');
	Route::resource('opposite_advocates','OpposingAdvocatesController');
	Route::resource('court_followup','CourtbookFollowupController');
	Route::resource('billing_type','BillingTypeController');
	Route::resource('practice_area','PracticeAreaController');
	Route::resource('matter_event','MatterEventController');
	Route::resource('party','PartyCOntroller');	
	Route::resource('communication','CommunicationController');
	Route::resource('billing','BillingController');
	Route::resource('matter_witness','MatterWitnessController');
 	Route::get('matter_details/{matter_id}','ExtraTaskController@matter_details');
 	Route::post('change_password','UserControoler@change_password');
 	Route::resource('user','UserControoler');
	Route::resource('alert','AlertController');
	Route::resource('event_user','EventUserController');
	Route::resource('logs','LoggingController');
	Route::resource('matter_authority','MatterAuthorityController');
	Route::resource('parnering_firms','PartneringFirmController');	
	Route::post('change_case_stage','ExtraTaskController@change_case_stage')->name('change_case_stage');
	Route::get('casees_report','ExtraTaskController@casees_report')->name('casees_report');
	Route::post('caseesreport','ExtraTaskController@caseesreport')->name('caseesreport');
	Route::post('matterreport','ExtraTaskController@matterreport')->name('matterreport');
	Route::get('matter_report','ExtraTaskController@matter_report')->name('matter_report');
	Route::post('clientreport','ExtraTaskController@clientreport')->name('clientreport');
	Route::get('client_report','ExtraTaskController@client_report')->name('client_report');
	Route::get('client_list','ExtraTaskController@client_list')->name('client_list');
	Route::post('change_matter_stage','ExtraTaskController@change_matter_stage')->name('change_matter_stage');
	Route::resource('case_types','CaseTypeController');
	Route::resource('company','CompanyController');
});//middleware

resources/views/calender/add_users.blade.php
@extends('layouts.master')

@section('content')
  <div class="card-box">
    <form method="POST" action="{{route('event_user.store')}}">
      @csrf

      <input type="hidden" name="matterevent_id" value="{{$event->id}}"> 
        <table class="table" id="billing">
          <thead>
            <th>#</th>  <th>Name</th> <th>Email</th> <th>Phone</th> <th>Action</th>
          </thead>

          <tbody>
              @foreach($users as $user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone_number}}</td>                          
                    <td>
                      <input type="checkbox" name="user[]" multiple="multiple" value="{{$user->id}}">
                    </td>                          
                </tr>                
              @endforeach
          </tbody>
      </table> 

      <button type="submit" class="btn btn-info">Save</button>
    </form>          
  </div>    
@endsection

resources/views/calender/calender.blade.php
@extends('layouts.master')

@section('content')
 <div class="card-box">
                   
        <div class="row">         
            <div class="col-md-12">
                <a href="{{route('matter_event.create')}}" class="btn btn-info">Show Events</a>
                <div id="calendar"></div>
            </div>
        </div>
    
        <div class="modal fade none-border" id="event-modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h3 class="h3">Add events</h3>
                    </div>
                    <div class="modal-body p-20">
                        
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-success save-event waves-effect waves-light">Create event</button>
                    </div>
                    
                </div>

            </div>
        </div>
    </div>  
@endsection

@push('scripts')
  <script>



    // var defaultEvents;
      !function($) {
        "use strict";
        
        var CalendarApp = function() {
            this.$body = $("body")
            this.$modal = $('#event-modal'),
            this.$event = ('#external-events div.external-event'),
            this.$calendar = $('#calendar'),
            this.$saveCategoryBtn = $('.save-category'),
            this.$categoryForm = $('#add-category form'),
            this.$extEvents = $('#external-events'),
            this.$calendarObj = null
        };


  
    CalendarApp.prototype.onDrop = function (eventObj, date) { 
        var $this = this;
            // retrieve the dropped element's stored Event Object
            var originalEventObject = eventObj.data('eventObject');
            var $categoryClass = eventObj.attr('data-class');
            // we need to copy it, so that multiple events don't have a reference to the same object
            var copiedEventObject = $.extend({}, originalEventObject);
            // assign it the date that was reported
            copiedEventObject.start = date;
            if ($categoryClass)
                copiedEventObject['className'] = [$categoryClass];
            // render the event on the calendar
            $this.$calendar.fullCalendar('renderEvent', copiedEventObject, true);
            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
                // if so, remove the element from the "Draggable Events" list
                eventObj.remove();
            }
    },
    /* on click on event */
    CalendarApp.prototype.onEventClick =  function (calEvent, jsEvent, view) {
 
            var $this = this;
            var form = $("<form></form>");
            form.append("<h5>"+calEvent.title+"</h5>");
            form.append("<p>"+calEvent.description+"</p>");
            form.append("<legend></legend>");
            form.append("<p> From: "+new Date(calEvent.start).toLocaleString()+"</p>");
            form.append("<p> To: "+new Date(calEvent.end).toLocaleString()+"</p>");         
           
            $this.$modal.modal({
                backdrop: 'static'
            });

            $this.$modal.find('.modal-body').empty().prepend(form).end().find('.save-event').hide().end().find('.h3').hide().end().click(function () {                
                $this.$modal.modal('hide');
            });
       },
    /* on select */
    CalendarApp.prototype.onSelect = function (start, end, allDay) {
        var $this = this;
            $this.$modal.modal({
                backdrop: 'static'
            });
            var form = $("<form></form>");
            form.append("<div class='row'></div>");
            form.find(".row")
                .append("<div class='col-md-12'><div class='form-group'><label class='control-label'>Title</label><input class='form-control' type='text' name='title'/></div></div>")
                .append("<div class='col-md-6'><div class='form-group'><label class='control-label'>Start Date</label><input type='date' class='form-control' name='start_date'/></div></div>")
                .append("<div class='col-md-6'><div class='form-group'><label class='control-label'>Start Time</label><input type='time' class='form-control' name='start_time'/></div></div>")
                .append("<div class='col-md-6'><div class='form-group'><label class='control-label'>End Date</label><input type='date' class='form-control' name='end_date'/></div></div>")
                .append("<div class='col-md-6'><div class='form-group'><label class='control-label'>End Time</label><input type='time' class='form-control' name='end_time'/></div></div>")
                .append("<div class='col-md-12'><div class='form-group'><label class='control-label'>Description</label><textarea class='form-control'  type='text' name='description'></textarea></div></div>")
                .find("select[name='category']")
                .append("</div></div>");
             $this.$modal.find('.delete-event').hide().end().find('.save-event').show().end().find('.modal-body').empty().prepend(form).end().find('.save-event').unbind('click').click(function () {
                form.submit();
            });
            $this.$modal.find('form').on('submit', function () {
                var title = form.find("input[name='title']").val();
                var description = form.find("textarea[name='description']").val();
                var start_date = form.find("input[name='start_date']").val();
                var start_time = form.find("input[name='start_time']").val();
                var end_date = form.find("input[name='end_date']").val();
                var end_time = form.find("input[name='end_time']").val();
                var categoryClass = form.find("select[name='category'] option:checked").val();
 
                if (title !== null && title.length != 0) {
                    $this.$calendarObj.fullCalendar('renderEvent', {
                        title:title,
                        start:start,
                        end: end,
                        allDay: false,
                        className: categoryClass
                    }, true);  
                    $this.$modal.modal('hide');

                    // save the invent
                $.ajax({
                    type: "POST",
                    url: "{!! route('matter_event.store') !!}",
                    data: { 
                        title:title,
                        description:description,
                        start:start_date,
                        start_time:start_time,
                        end:end_date,
                        end_time:end_time,
                        _token: "{{Session::token()}}" },
                    success: function(result){
                        console.log(result);
                    }
                });

                }
                else{
                    alert('You have to give a title to your event');
                }
                return false;
                
            });
            $this.$calendarObj.fullCalendar('unselect');
    },
    CalendarApp.prototype.enableDrag = function() {
        //init events
        $(this.$event).each(function () {
            // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
            // it doesn't need to have a start or end
            var eventObject = {
                title: $.trim($(this).text()) // use the element's text as the event title
            };
            // store the Event Object in the DOM element so we can get to it later
            $(this).data('eventObject', eventObject);
            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 999,
                revert: true,      // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });
        });
    }
    /* Initializing */
    CalendarApp.prototype.init = function() {
        this.enableDrag();
        /*  Initialize the calendar  */
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        var form = '';
        var today = new Date($.now());

        // console.log("Today: "+today);

        var defaultEvents;

      
            $.ajax({
                async: false,
                type: "GET",
                
                url: "{!! route('matter_event.show','user_events') !!}",
                data: { 
                    _token: "{{Session::token()}}" },
                success: function(result){
                   defaultEvents=result; 

              }

            });

                var $this = this;
 
                $this.$calendarObj = $this.$calendar.fullCalendar({                    
                    events:defaultEvents,
                    slotDuration: '00:15:00', /* If we want to split day time each 15minutes */
                    minTime: '08:00:00',
                    maxTime: '19:00:00',  
                    defaultView: 'month',  
                    handleWindowResize: true,   
                    height: $(window).height() - 200,   
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,agendaWeek,agendaDay'
                    },
                    
                    editable: true,
                    droppable: true, // this allows things to be dropped onto the calendar !!!
                    eventLimit: true, // allow "more" link when too many events
                    selectable: true,
                    drop: function(date) { $this.onDrop($(this), date); },
                    select: function (start, end, allDay) { $this.onSelect(start, end, allDay); },
                    eventClick: function(calEvent, jsEvent, view) { $this.onEventClick(calEvent, jsEvent, view); }

                });
            
       

           
         
        

        //on new event
        this.$saveCategoryBtn.on('click', function(){
            var categoryName = $this.$categoryForm.find("input[name='category-name']").val();
            var categoryColor = $this.$categoryForm.find("select[name='category-color']").val();
            if (categoryName !== null && categoryName.length != 0) {
                $this.$extEvents.append('<div class="external-event bg-' + categoryColor + '" data-class="bg-' + categoryColor + '" style="position: relative;"><i class="fa fa-move"></i>' + categoryName + '</div>')
                $this.enableDrag();
            }

        });
    },

   //init CalendarApp
    $.CalendarApp = new CalendarApp, $.CalendarApp.Constructor = CalendarApp
    
}(window.jQuery),

//initializing CalendarApp
function($) {
    "use strict";
    $.CalendarApp.init()
}(window.jQuery);



  </script>
@endpush

resources/views/calender/events.blade.php
@extends('layouts.master')

@section('content')
<div class="card-box">
    

            <table class="table" id="billing">
                <thead>
                  <th>#</th>  <th>Title</th> <th>Body</th> <th>From</th> <th>To</th> <th>Users</th> <th>Action</th>
                </thead>

                <tbody>
                    @foreach($events as $event)
                      <tr>
                          <td>{{$event->id}}</td>
                          <td>{{$event->title}}</td>
                          <td>{{$event->description}}</td>
                          <td>{{$event->start}}</td>
                          <td>{{$event->end}}</td>

                          <td>
                              @foreach($event->eventuser as $users)
                                {{$users->user->name}},  
                              @endforeach
                          </td>
                          <td>
                             <form action="/matter_event/{{ $event->id }}" method="POST">
                                    {{method_field('DELETE')}}
                                    {{ csrf_field() }}
                                       <a href="{{route('matter_event.edit',$event->id)}}" class="btn btn-info">Add Users</a>
                                    <input type="submit" class="btn btn-danger" value="Delete"/>
                                </form>
                            
                        </td>
                          
                      </tr>


                
                    @endforeach
                </tbody>
            </table>           
        </div>
@endsection